// Generated by CoffeeScript 1.9.2
var debounce, lsqueue, store;

require('json-fallback');

debounce = require('debounce');

store = require('store.js');


/**
 * a queue backed by localStorage
 * new queue("name")
 */

lsqueue = (function() {
  function lsqueue(name) {
    var self;
    self = this;
    self.qn = name || "queue";
    self.items = [];
    return self;
  }

  lsqueue.prototype.persist = function() {
    var self;
    self = this;
    if (!store.enabled) {
      return self;
    }
    try {
      store.set(self.qn, self.items);
    } catch (_error) {

    }
    return self;
  };

  lsqueue.prototype.push = function(v) {
    var self;
    self = this;
    self.items.push(v);
    (debounce(function() {
      return self.persist();
    }, 111))();
    return self;
  };

  lsqueue.prototype.pop = function() {
    var self;
    self = this;
    if (self.items.length > 0) {
      (debounce(function() {
        return self.persist();
      }, 111))();
      return self.items.shift();
    }
  };

  lsqueue.prototype.clear = function() {
    var self;
    self = this;
    self.items = [];
    (debounce(function() {
      return self.persist();
    }, 111))();
    return self;
  };

  return lsqueue;

})();

module.exports = lsqueue;
